src/Entity/AccountType.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AccountTypeRepository")
 */
class AccountType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $username;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $IsCustomer;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $IsContractor;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?user
    {
        return $this->username;
    }

    public function setUsername(user $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getIsCustomer(): ?bool
    {
        return $this->IsCustomer;
    }

    public function setIsCustomer(bool $IsCustomer): self
    {
        $this->IsCustomer = $IsCustomer;

        return $this;
    }

    public function getIsContractor(): ?bool
    {
        return $this->IsContractor;
    }

    public function setIsContractor(?bool $IsContractor): self
    {
        $this->IsContractor = $IsContractor;

        return $this;
    }
}

src/Entity/Ord.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrdRepository")
 */
class Ord
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $customer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", fetch="EAGER")
     */
    private $contractor;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_active;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ordname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $orddesc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ordprice;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomer(): ?User
    {
        return $this->customer;
    }

    public function setCustomer(?User $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getContractor(): ?User
    {
        return $this->contractor;
    }

    public function setContractor(?User $contractor): self
    {
        $this->contractor = $contractor;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getOrdname(): ?string
    {
        return $this->ordname;
    }

    public function setOrdname(string $ordname): self
    {
        $this->ordname = $ordname;

        return $this;
    }

    public function getOrddesc(): ?string
    {
        return $this->orddesc;
    }

    public function setOrddesc(string $orddesc): self
    {
        $this->orddesc = $orddesc;

        return $this;
    }

    public function getOrdprice(): ?string
    {
        return $this->ordprice;
    }

    public function setOrdprice(string $ordprice): self
    {
        $this->ordprice = $ordprice;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/mainpage.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Mainpage</title>
</head>
<body>
  <a href="/signup"><button>Sign up</button></a>
  <a href="/signin"><button>Sign in</button></a>
</body>
</html>

templates/neworder.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>New Order</title>
</head>
<body>
  <form action="/orders" method="POST">
    <fieldset>
      <label for="ordname">order name</label>
      <input type="text" name="ordname" required>
      <label for="orddesc">order desc</label>
      <textarea name="orddesc" cols="50" rows="5" required></textarea>
      <label for="ordprice">order price</label>
      <input type="text" name="ordprice" required>
      <input type="hidden" name="form_id" value="new_order">
      <input type="hidden" name="user_id" value="{{ user_id }}">
      <input type="submit" value="add order">
    </fieldset>
  </form>
</body>
</html>

templates/orders.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Orders</title>
  <style>
    table {
      border-collapse: collapse;
    }
    table, th, td {
      border: 1px solid black;
    }
    td #is-taken {
      width: 100px;
      text-align: center;
    }
  </style>
  <script>
    document.addEventListener("DOMContentLoaded", function(e) {
      if ({{ account_type.isContractor|json_encode}}) {
        var ords = document.getElementsByClassName("ord");

        var xhr = new XMLHttpRequest();
        for (var i = 0; i < ords.length; i++) {
          (function () {

            var ordid = ords[i].cells[0].textContent;
            var takeButton = ords[i].cells[4].children[0];
            var closeButton = ords[i].cells[4].children[1];

            var res = null;

            takeButton.addEventListener("click", function() {
              console.log("take -> order id: " + ordid);
              xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                  if (xhr.status === 200) {
                    console.log("take -> req is completed, code: 200");
                    res = JSON.parse(xhr.response);
                    console.log(res.status);
                    if (res.status === "SUCCESS") {
                      takeButton.disabled = true;
                      closeButton.disabled = false;
                    } else {
                      alert(res.message);
                    }
                  }
                }
              }
              // xhr.open("GET", "/orders/take?ordid=" + ordid);
              // xhr.send();
              xhr.open("POST", "/orders/take");
              // xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
              xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
              xhr.send("action=take&ordid=" + ordid + "&userid=" + {{ user_id|json_encode }});
            });

            closeButton.addEventListener("click", function() {
              console.log("close -> order id: " + ordid);
              xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                  if (xhr.status === 200) {
                    console.log("close -> req is completed, code: 200");
                    res = JSON.parse(xhr.response);
                    console.log(res.status);
                    if (res.status === "SUCCESS") {
                      takeButton.disabled = false;
                      closeButton.disabled = true;
                    } else {
                      alert(res.message);
                    }
                  }
                }
              }
              xhr.open("POST", "/orders/take");
              // xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
              xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
              xhr.send("action=close&ordid=" + ordid + "&userid=" + {{ user_id|json_encode }});
            });

          }());
        }
      }

    });
  </script>
</head>
<body>
  {% if account_type.isCustomer %}
  <a href="/orders/new?user_id={{ user_id }}"><button>new order</button></a>
  {% endif %}
  <table>
    <tr>
      <th>ID</th>
      <th>Order</th>
      <th>Description</th>
      <th>Price</th>
      {% if account_type.isCustomer %}
      <th>Contractor</th>
      {% endif %}
      {% if account_type.isContractor %}
      <th>In process?</th>
      {% endif %}
    </tr>
    {% for order in orders %}
    <tr class="ord">
      <td id="ord-id">{{ order.id }}</td>
      <td>{{ order.ordname }}</td>
      <td>{{ order.orddesc }}</td>
      <td>{{ order.ordprice }}</td>
      {% if account_type.isCustomer %}
      <td> {{ order.contractor ? order.contractor.username }}</td>
      {% else %}
      <td>
        <button id="take"
          {% if order.isActive %}
            disabled
          {% endif %}
        >
          take
        </button>
        <button id="close"
          {% if not(order.contractor) or (order.contractor.id != user_id) %}
            disabled
          {% endif %}
        >
          close
        </button>
      </td>
      {% endif %}
    </tr>
    {% endfor %}
  </table>
</body>
</html>

templates/signin.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Signin</title>
</head>
<body>
  <p>Signin page</p>
  <form action="/orders" method="POST">
    <fieldset>
      <label for="username">username</label>
      <input type="text" name="username" required>
      <label for="password">password</label>
      <input type="password" name="password">
      <input type="hidden" name="form_id" value="sin">
      <input type="submit" value="sign in">
    </fieldset>
  </form>
  </form>
</body>
</html>

templates/signup.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Signup</title>
</head>
<body>
  <p>Signup page</p>
  <form action="/orders" method="POST">
    <fieldset>
      <label for="username">username</label>
      <input type="text" name="username" required>
      <label for="password">password</label>
      <input type="password" name="password" required>
      <br>
      <input type="radio" name="account_type" value="customer" checked>customer
      <br>
      <input type="radio" name="account_type" value="contractor">contractor
      <br>
      <input type="hidden" name="form_id" value="sup">
      <input type="submit" value="sign up">
    </fieldset>
  </form>
</body>
</html>